// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zwgqdWza9BwtUU0OzxwsmIAQGJSLw2o',
    appId: '1:460399022122:web:7ddf99d6689200031ef353',
    messagingSenderId: '460399022122',
    projectId: 'smartshade-8442c',
    authDomain: 'smartshade-8442c.firebaseapp.com',
    databaseURL: 'https://smartshade-8442c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshade-8442c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAgeU7vAdLCipQh9IE4zLoaMAfoygAqs',
    appId: '1:460399022122:android:846cc9c1cacbdbfb1ef353',
    messagingSenderId: '460399022122',
    projectId: 'smartshade-8442c',
    databaseURL: 'https://smartshade-8442c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshade-8442c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIi1V5zKNtj7HoYe-vAK6jqEdcqYC_Uyk',
    appId: '1:460399022122:ios:e983d3432878f29e1ef353',
    messagingSenderId: '460399022122',
    projectId: 'smartshade-8442c',
    databaseURL: 'https://smartshade-8442c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshade-8442c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIi1V5zKNtj7HoYe-vAK6jqEdcqYC_Uyk',
    appId: '1:460399022122:ios:1c08b4b2c8ed439e1ef353',
    messagingSenderId: '460399022122',
    projectId: 'smartshade-8442c',
    databaseURL: 'https://smartshade-8442c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartshade-8442c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
